server:
  port: 8081
  servlet:
    context-path: /rest
wechat:
  appid: wxb0ea561ede9f99f8
  appsecret: 43fb8393bbca2c96f7bfeee58e17c6da
  token: zhanglun
  access-token-url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  menu-create-url: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN
spring:
  aop:
    auto: true
logging:
  file: log/wxgzh.log
