server:
  port: 8081
  servlet:
    context-path: /rest
wechat:
  appid: wx3e1f21cfe533fc0d
  appsecret: 939ed159b421e84ceeb46fd89de72a91
  token: zhanglun
  access-token-url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=APPID&secret=APPSECRET
  menu-create-url: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=ACCESS_TOKEN
spring:
  aop:
    auto: true
logging:
  file: log/wxgzh.log